const D=window.GAME_DATA;
const API='https://cgyyagoxbgzneuqxcbqr.supabase.co/functions/v1/game-api';
const FINAL_STAGE=Math.max(...D.stages.map(s=>s.id));
const CAL_OPTIONS=['Ні','Спірно','Має ознаки зловживання'];
const CAL=[
  'Після відмови у клопотанні сторона подає його повторно. Предмет той самий, але додано нову фактичну обставину, яка виникла після попередньої ухвали.',
  'За три дні до завершення підготовчого провадження сторона подає близько 600 сторінок технічних документів, якими володіла ще до звернення до суду, пояснюючи, що лише тепер зрозуміла їх значення.',
  'Після відмови у відкладенні сторона заявляє відвід. Більшість доводів стосується незгоди з процесуальними рішеннями судді, але один новий факт об’єктивно став відомий лише напередодні.',
  'Після несприятливої проміжної ухвали сторона одночасно подає апеляційну скаргу, заяву про роз’яснення та нове клопотання, яке фактично спрямоване на досягнення того самого процесуального результату.',
  'У процесуальному документі представник пише: «Суддя демонструє такий рівень правової необізнаності та упередженості, який є несумісним із належним здійсненням правосуддя».'
];
const state={role:null,teamId:null,accessCode:null,openedStage:0,viewedStage:0,responses:{},scores:{A:0,B:0,C:0},finalSubmittedCount:0};
let syncTimer=null;
function el(id){return document.getElementById(id)}
function esc(s=''){return String(s).replace(/[&<>\'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
function stg(id){return D.stages.find(s=>s.id===Number(id))||D.stages[0]}
function current(){return stg(state.viewedStage)}
function unlocked(s){return s.id<=state.openedStage}
function key(team,stageId){return `${team}-${stageId}`}
function response(team,stageId){return state.responses[key(team,stageId)]||null}
function formatTime(v){if(!v)return '';try{return new Intl.DateTimeFormat('uk-UA',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch{return ''}}
async function api(action,payload={}){const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,code:state.accessCode,...payload})});let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.error||'Помилка сервера');return d}
function mapScores(rows=[]){for(const t of D.teams)state.scores[t.id]=0;for(const r of rows)state.scores[r.team_id]=Number(r.score)||0}
function mapResponses(rows=[]){state.responses={};for(const r of rows)state.responses[key(r.team_id,r.stage_id)]={answer:r.answer,submittedAt:r.submitted_at,updatedAt:r.updated_at}}
async function syncData(){if(!state.role)return;if(state.role==='trainer'){const d=await api('trainerDashboard');state.openedStage=d.openedStage||0;state.finalSubmittedCount=d.finalSubmittedCount||0;mapResponses(d.responses||[]);mapScores(d.scores||[])}else{const [mine,all]=await Promise.all([api('myResponses'),api('state')]);state.openedStage=all.openedStage||0;state.finalSubmittedCount=all.finalSubmittedCount||0;mapScores(all.scores||[]);mapResponses((mine.responses||[]).map(r=>({...r,team_id:state.teamId})))}if(state.viewedStage>state.openedStage)state.viewedStage=state.openedStage}
function startSync(){if(syncTimer)clearInterval(syncTimer);syncTimer=setInterval(async()=>{try{await syncData();render()}catch{}},4000)}
function login(){let role='team';el('app').innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-top"><div class="login-brand"><div class="nsju-logo-wrap login-emblem"><img class="nsju-logo" src="nsju-emblem.png?v=4" alt="Емблема Національної школи суддів України"></div><div><div class="eyebrow" style="color:#e6c89a;margin-bottom:6px">Суддівська симуляція</div><h1>${esc(D.title)}</h1><p>${esc(D.subtitle)}</p></div></div></div><div class="login-body"><div class="role-tabs"><button id="rt" class="role-tab active">Команда</button><button id="rr" class="role-tab">Тренер</button></div><div class="field"><label id="codeLabel">Код команди</label><input id="loginCode" autocomplete="off" placeholder="Введіть код доступу"></div><button id="loginBtn" class="btn burgundy" style="width:100%">Увійти до симуляції</button><div id="loginError" class="small" style="color:var(--danger);margin-top:12px"></div></div></div></div>`;el('rt').onclick=()=>{role='team';el('rt').classList.add('active');el('rr').classList.remove('active');el('codeLabel').textContent='Код команди'};el('rr').onclick=()=>{role='trainer';el('rr').classList.add('active');el('rt').classList.remove('active');el('codeLabel').textContent='Код тренера'};el('loginBtn').onclick=async()=>{const code=el('loginCode').value.trim();if(!code)return;el('loginBtn').disabled=true;el('loginError').textContent='Перевіряю доступ…';try{state.accessCode=code;const d=await api('login');if(d.role!==role)throw new Error(role==='trainer'?'Це не код тренера':'Це не код команди');state.role=d.role;state.teamId=d.teamId||null;state.openedStage=d.openedStage||0;state.viewedStage=state.openedStage;state.finalSubmittedCount=d.finalSubmittedCount||0;mapScores(d.scores||[]);sessionStorage.setItem('processAbuseCode',code);await syncData();startSync();render()}catch(e){state.accessCode=null;el('loginError').textContent=e.message;el('loginBtn').disabled=false}}}
function topbar(){const team=D.teams.find(t=>t.id===state.teamId);return `<header class="masthead"><div class="masthead-inner"><div class="identity"><div class="nsju-logo-wrap compact"><img class="nsju-logo" src="nsju-emblem.png?v=4" alt="Емблема НШСУ"></div><div class="brand">${esc(D.title)}<small>${esc(D.subtitle)}</small></div></div><div class="top-actions"><span class="pill">${state.role==='trainer'?'Панель тренера':esc(team?.name||'')}</span><button class="btn secondary small-btn" onclick="logout()">Вийти</button></div></div></header>`}
window.logout=()=>{if(syncTimer)clearInterval(syncTimer);sessionStorage.removeItem('processAbuseCode');Object.assign(state,{role:null,teamId:null,accessCode:null,responses:{}});render()}
window.goStage=id=>{const s=stg(id);if(unlocked(s)){state.viewedStage=s.id;render()}}
function nav(){return `<div class="stage-shell"><div class="timeline">${D.stages.map(s=>`<button class="stage-chip ${s.id===state.viewedStage?'active':''} ${unlocked(s)?'':'locked'}" ${unlocked(s)?`onclick="goStage(${s.id})"`:'disabled'}><span class="stage-state">${unlocked(s)?(s.id===state.openedStage?'поточний':'відкрито'):'закрито'}</span><strong>${esc(s.kind)}</strong><span>${esc(s.title)}</span></button>`).join('')}</div></div>`}
function abuseMap(s){return `<div class="abuse-map">${D.abuseTypes.map(x=>`<span class="abuse-chip ${s.abuse.includes(x)?'active':''}">${esc(x)}</span>`).join('')}</div>`}
function docCard(d){return `<div class="doc"><div class="doc-left"><div class="doc-icon ${d.tone==='burgundy'?'burgundy':''}">${esc(d.icon||'▤')}</div><div><div class="doc-title">${esc(d.title)}</div><div class="doc-meta">${esc(d.meta||'')}</div><div class="tag-row">${(d.tags||[]).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></div></div><button class="btn ghost small-btn" onclick="openDoc('${d.id}')">Відкрити</button></div>`}
window.openDoc=id=>{const d=D.stages.flatMap(s=>s.docs||[]).find(x=>x.id===id);if(!d)return;document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="docModal"><div class="modal"><div class="modal-bar"></div><div class="modal-content"><div class="modal-head"><div><div class="section-kicker">Матеріал справи</div><h2>${esc(d.title)}</h2><p class="muted">${esc(d.meta||'')}</p></div><button class="btn secondary" onclick="el('docModal').remove()">Закрити</button></div><div class="doc-body">${esc(d.body)}</div></div></div></div>`)}
function hero(s){return `<div class="banner"><div class="hero-card"><div class="eyebrow">${esc(s.kind)} · ${esc(s.time)}</div><h1>${esc(s.title)}</h1><p>${esc(s.intro)}</p><div class="hero-meta"><span class="meta-chip">${esc(D.caseNo)}</span><span class="meta-chip">Господарська юрисдикція</span><span class="meta-chip">Наскрізна справа</span></div>${s.lecture?`<div class="notice blue"><strong>Міні-лекція:</strong> ${esc(s.lecture)}</div>`:''}</div><div class="progress-card"><div class="progress-label">Відкрито етапів</div><div class="score">${state.openedStage+1}/${D.stages.length}</div><div class="progress"><div style="width:${Math.round((state.openedStage/(D.stages.length-1))*100)}%"></div></div><p class="small" style="color:#d9e4eb;margin-top:10px">Відповіді зберігаються у спільній базі даних.</p></div></div>`}
function caseSide(s,team){return `<div class="card side-case"><div class="section-kicker">Електронне досьє</div><h3>${esc(team?.name||'Симуляційна справа')}</h3><div class="case-number">${esc(D.caseNo)}</div><div class="case-list"><div class="case-item"><span>Сторони</span><b>${esc(D.parties)}</b></div><div class="case-item"><span>Предмет</span><b>${esc(D.subject)}</b></div><div class="case-item"><span>Переглядається</span><b>${esc(s.kind)}: ${esc(s.title)}</b></div></div></div><div class="card"><div class="section-kicker">Карта ризиків</div><h3 style="margin-bottom:12px">Потенційні види зловживань</h3>${abuseMap(s)}</div>`}
function calibrationForm(){const r=response(state.teamId,0);const a=r?.answer&&typeof r.answer==='object'?r.answer:{};const done=!!r;return `<div class="task-box"><div class="section-kicker">Калібрування</div><h3>Зловживання чи ні?</h3><p>Оцініть усі п’ять ситуацій. Правильної відповіді на цьому етапі навмисно немає.</p><div class="cal-list">${CAL.map((q,i)=>`<div class="cal-item"><div class="cal-num">${i+1}</div><div><p>${esc(q)}</p><div class="cal-grid">${CAL_OPTIONS.map(o=>`<label class="option"><input type="radio" name="cal-${i}" value="${esc(o)}" ${a['q'+(i+1)]===o?'checked':''} ${done?'disabled':''}><span>${esc(o)}</span></label>`).join('')}</div></div></div>`).join('')}</div><button class="btn burgundy" ${done?'disabled':''} onclick="submitCalibration()">${done?'Калібрування подано':'Подати 5 відповідей'}</button>${done?`<p class="status ok">Зафіксовано ${formatTime(r.submittedAt)}</p>`:''}</div>`}
function taskForm(s){if(s.id===0)return calibrationForm();const r=response(state.teamId,s.id),done=!!r;return `<div class="task-box"><div class="section-kicker">Завдання команди</div><h3>${esc(s.task.title)}</h3><p>${esc(s.task.prompt)}</p><div class="field"><textarea id="answerText" ${done?'disabled':''} placeholder="Введіть узгоджену позицію команди...">${esc(r?.answer||'')}</textarea></div><button class="btn burgundy" ${done?'disabled':''} onclick="submitText(${s.id})">${done?'Відповідь подано':'Подати відповідь'}</button>${done?`<p class="status ok">Відповідь зафіксовано ${formatTime(r.submittedAt)}</p>`:''}</div>`}
window.submitCalibration=async()=>{const a={};for(let i=0;i<CAL.length;i++){const v=document.querySelector(`input[name="cal-${i}"]:checked`)?.value;if(!v)return alert(`Дайте відповідь на ситуацію ${i+1}`);a['q'+(i+1)]=v}try{await api('submit',{stageId:0,answer:a});await syncData();render()}catch(e){alert(e.message)}}
window.submitText=async id=>{const v=el('answerText').value.trim();if(!v)return alert('Введіть відповідь команди');try{await api('submit',{stageId:id,answer:v});await syncData();render()}catch(e){alert(e.message)}}
function scoreboard(){if(state.openedStage<FINAL_STAGE||state.finalSubmittedCount<3)return '';const rows=D.teams.map(t=>({name:t.name,score:state.scores[t.id]||0})).sort((a,b)=>b.score-a.score);return `<section class="card final-score"><div class="section-kicker">Підсумок тренінгу</div><h2>Підсумковий рахунок команд</h2><div class="scoreboard">${rows.map((r,i)=>`<div class="score-row"><div class="place">${i+1}</div><div><strong>${esc(r.name)}</strong><span>Фінальний результат</span></div><b>${r.score}</b></div>`).join('')}</div></section>`}
function teamView(){const s=current(),team=D.teams.find(t=>t.id===state.teamId),asym=s.asymmetric?.[state.teamId];return `<div class="shell">${topbar()}<main class="container">${hero(s)}${nav()}${scoreboard()}<div class="layout"><div class="stack"><section class="card"><div class="card-title"><div><div class="section-kicker">Матеріали етапу</div><h2>Документи та процесуальні події</h2></div><span class="meta-chip">${(s.docs||[]).length} матеріалів</span></div><div class="docs">${(s.docs||[]).length?s.docs.map(docCard).join(''):'<div class="notice">На калібрувальному етапі досьє ще не відкривається.</div>'}</div>${asym?`<div class="notice burgundy"><strong>${esc(asym.title)}</strong><br>${esc(asym.body)}</div>`:''}</section><section class="card">${taskForm(s)}</section></div><aside class="stack">${caseSide(s,team)}<div class="card"><div class="section-kicker">Результат</div><h3>Бали команди</h3><div class="score" style="color:var(--burgundy)">${state.scores[state.teamId]||0}</div></div></aside></div></main>${footer()}</div>`}
function trainerAnswer(t,s){const r=response(t.id,s.id);if(!r)return `<div class="trainer-response empty"><div class="resp-head"><div><span class="team-badge">${t.id}</span><strong>${esc(t.name)}</strong></div><span class="status warn">Не подано</span></div><div class="muted">Відповідь команди ще не надходила.</div></div>`;if(s.id===0){const a=r.answer||{};return `<div class="trainer-response"><div class="resp-head"><div><span class="team-badge">${t.id}</span><strong>${esc(t.name)}</strong><span class="resp-time">${formatTime(r.submittedAt)}</span></div><span class="status ok">Подано 5/5</span></div>${CAL.map((q,i)=>`<div class="cal-result"><b>${i+1}</b><span>${esc(q)}</span><strong>${esc(a['q'+(i+1)]||'Немає відповіді')}</strong></div>`).join('')}<div class="score-edit"><span>Загальні бали:</span><input id="score-${t.id}" type="number" min="0" value="${state.scores[t.id]||0}"><button class="btn secondary small-btn" onclick="setScore('${t.id}')">Зберегти</button></div></div>`}return `<div class="trainer-response"><div class="resp-head"><div><span class="team-badge">${t.id}</span><strong>${esc(t.name)}</strong><span class="resp-time">${formatTime(r.submittedAt)}</span></div><span class="status ok">Подано</span></div><div class="resp-full">${esc(r.answer)}</div><div class="score-edit"><span>Загальні бали:</span><input id="score-${t.id}" type="number" min="0" value="${state.scores[t.id]||0}"><button class="btn secondary small-btn" onclick="setScore('${t.id}')">Зберегти</button></div></div>`}
function trainerView(){const s=current(),submitted=D.teams.filter(t=>!!response(t.id,s.id)).length;return `<div class="shell">${topbar()}<main class="container">${hero(s)}${nav()}${scoreboard()}<div class="trainer-grid"><div class="metric"><span class="muted small">Переглядається</span><b>${esc(s.kind)}</b><span class="small">${esc(s.title)}</span></div><div class="metric"><span class="muted small">Подали відповідь</span><b>${submitted}/${D.teams.length}</b><span class="small">команд на цьому етапі</span></div><div class="metric"><span class="muted small">Наступний етап</span><b>${state.openedStage<FINAL_STAGE?esc(D.stages[state.openedStage+1].kind):'Фінал відкрито'}</b><button class="btn burgundy small-btn" style="margin-top:8px" ${state.openedStage>=FINAL_STAGE?'disabled':''} onclick="openNext()">Відкрити</button></div></div><div style="height:20px"></div><div class="layout"><div class="stack"><div class="card"><div class="card-title"><div><div class="section-kicker">Команди</div><h2>Повні відповіді команд</h2></div><button class="btn ghost small-btn" onclick="manualRefresh()">Оновити</button></div><div class="trainer-responses">${D.teams.map(t=>trainerAnswer(t,s)).join('')}</div></div><div class="card"><div class="section-kicker">Матеріали</div><h2 style="margin-bottom:14px">Поточний пакет</h2><div class="docs">${(s.docs||[]).map(docCard).join('')||'<p class="muted">Документів немає.</p>'}</div></div></div><aside class="stack">${caseSide(s,null)}<div class="card"><div class="section-kicker">Стан фіналу</div><h3>Фінальні позиції</h3><div class="score" style="color:var(--burgundy)">${state.finalSubmittedCount}/3</div><p class="small muted">Підсумковий рахунок автоматично з’явиться для всіх після подання фінальної відповіді всіма командами.</p></div></aside></div></main>${footer()}</div>`}
window.openNext=async()=>{if(state.openedStage>=FINAL_STAGE)return;try{await api('openNext',{openedStage:state.openedStage+1});await syncData();state.viewedStage=state.openedStage;render()}catch(e){alert(e.message)}}
window.setScore=async teamId=>{const v=Number(el(`score-${teamId}`)?.value);if(!Number.isFinite(v)||v<0)return alert('Введіть коректний бал');try{await api('setScore',{teamId,score:v});await syncData();render()}catch(e){alert(e.message)}}
window.manualRefresh=async()=>{try{await syncData();render()}catch(e){alert(e.message)}}
function footer(){return `<footer class="site-footer"><div class="site-footer-inner"><div class="footer-brand"><img src="nsju-emblem.png?v=4" alt="Емблема НШСУ"><div><strong>Національна школа суддів України</strong><span>Навчальна інтерактивна симуляція</span></div></div><div class="credit">Розроблено <strong>Оленою Фоновою</strong>, 2026</div></div></footer>`}
function render(){if(!state.role){login();return}el('app').innerHTML=state.role==='trainer'?trainerView():teamView()}
async function boot(){const saved=sessionStorage.getItem('processAbuseCode');if(saved){try{state.accessCode=saved;const d=await api('login');state.role=d.role;state.teamId=d.teamId||null;state.openedStage=d.openedStage||0;state.viewedStage=state.openedStage;state.finalSubmittedCount=d.finalSubmittedCount||0;mapScores(d.scores||[]);await syncData();startSync()}catch{sessionStorage.removeItem('processAbuseCode')}}render()}
boot();