const D=window.GAME_DATA;
const key='processAbuseGameV2';
const defaults={role:null,teamId:null,openedStage:0,viewedStage:0,answers:{},scores:{A:0,B:0,C:0},submitted:{},finalScoreboardVisible:false};
const state=Object.assign({},defaults,JSON.parse(localStorage.getItem(key)||'{}'));
function save(){localStorage.setItem(key,JSON.stringify(state))}
function el(id){return document.getElementById(id)}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function stageById(id){return D.stages.find(s=>s.id===id)||D.stages[0]}
function viewed(){return stageById(state.viewedStage)}
function stageUnlocked(s){return s.id<=state.openedStage}
function progressPct(){return Math.round((state.openedStage/(D.stages.length-1))*100)}
function isFinalStage(s){return s.id===D.stages[D.stages.length-1].id}
const NSJU_LOGO='/nsju-emblem.png?v=20260929-1';
function login(){
  let role='team';
  el('app').innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-top"><div class="login-brand"><div class="nsju-logo-wrap"><img class="nsju-logo" src="${NSJU_LOGO}" alt="Емблема Національної школи суддів України"></div><div><div class="eyebrow" style="color:#e6c89a;margin-bottom:6px">Суддівська симуляція</div><h1>${D.title}</h1><p>${D.subtitle}</p></div></div></div><div class="login-body"><div class="role-tabs"><button id="rt" class="role-tab active">Команда</button><button id="rr" class="role-tab">Тренер</button></div><div class="field"><label id="codeLabel">Код команди</label><input id="loginCode" placeholder="Наприклад TEAM-A" /></div><button id="loginBtn" class="btn burgundy" style="width:100%">Увійти до симуляції</button><div class="demo-note small">Демо-коди: TEAM-A, TEAM-B, TEAM-C. Код тренера: TRAINER-2026.</div></div></div></div>`;
  el('rt').onclick=()=>{role='team';el('rt').classList.add('active');el('rr').classList.remove('active');el('codeLabel').textContent='Код команди'};
  el('rr').onclick=()=>{role='trainer';el('rr').classList.add('active');el('rt').classList.remove('active');el('codeLabel').textContent='Код тренера'};
  el('loginBtn').onclick=()=>{const c=el('loginCode').value.trim();if(role==='trainer'&&c===D.trainerCode){state.role='trainer';state.viewedStage=state.openedStage;save();render();return}const t=D.teams.find(x=>x.code===c);if(role==='team'&&t){state.role='team';state.teamId=t.id;state.viewedStage=Math.min(state.viewedStage,state.openedStage);save();render();return}alert('Невірний код входу')};
}
function topbar(){const team=D.teams.find(t=>t.id===state.teamId);return `<header class="masthead"><div class="masthead-inner"><div class="identity"><div class="nsju-logo-wrap compact"><img class="nsju-logo" src="${NSJU_LOGO}" alt="Емблема Національної школи суддів України"></div><div class="brand">${D.title}<small>${D.subtitle}</small></div></div><div class="top-actions"><span class="pill">${state.role==='trainer'?'Панель тренера':team?.name||''}</span><button class="btn secondary small-btn" onclick="logout()">Вийти</button></div></div></header>`}
window.logout=()=>{state.role=null;state.teamId=null;save();render()}
window.goStage=id=>{const s=stageById(Number(id));if(!stageUnlocked(s))return;state.viewedStage=s.id;save();render()}
function stageNav(){return `<div class="stage-shell"><div class="timeline">${D.stages.map(s=>`<button class="stage-chip ${s.id===state.viewedStage?'active':''} ${stageUnlocked(s)?'':'locked'}" ${stageUnlocked(s)?`onclick="goStage(${s.id})"`:'disabled'}><span class="stage-state">${stageUnlocked(s)?(s.id===state.openedStage?'поточний':'відкрито'):'закрито'}</span><strong>${s.kind}</strong><span>${s.title}</span></button>`).join('')}</div></div>`}
function abuseMap(s){return `<div class="abuse-map">${D.abuseTypes.map(x=>`<span class="abuse-chip ${s.abuse.includes(x)?'active':''}">${escapeHtml(x)}</span>`).join('')}</div>`}
function docCard(d){const tags=(d.tags||[]).map(t=>`<span class="tag ${t==='AI'||t==='неповага'?'red':t==='забезпечення'||t==='пізні докази'?'warm':''}">${escapeHtml(t)}</span>`).join('');return `<div class="doc"><div class="doc-left"><div class="doc-icon ${d.tone==='burgundy'?'burgundy':''}">${escapeHtml(d.icon||'▤')}</div><div><div class="doc-title">${escapeHtml(d.title)}</div><div class="doc-meta">${escapeHtml(d.meta||'')}</div><div class="tag-row">${tags}</div></div></div><button class="btn ghost small-btn" onclick="openDoc('${d.id}')">Відкрити</button></div>`}
window.openDoc=id=>{const d=D.stages.flatMap(s=>s.docs||[]).find(x=>x.id===id);if(!d)return;document.body.insertAdjacentHTML('beforeend',`<div class="overlay" id="docModal"><div class="modal"><div class="modal-bar"></div><div class="modal-content"><div class="modal-head"><div><div class="section-kicker">Матеріал справи</div><h2>${escapeHtml(d.title)}</h2><p class="muted">${escapeHtml(d.meta||'')}</p></div><button class="btn secondary" onclick="el('docModal').remove()">Закрити</button></div><div class="doc-body">${escapeHtml(d.body)}</div></div></div></div>`)}
function taskForm(s){const k=`${state.teamId}-${s.id}`;const existing=state.answers[k]||'';const done=!!state.submitted[k];if(s.task.type==='choice')return `<div class="task-box"><div class="section-kicker">Завдання команди</div><h3>${s.task.title}</h3><p>${s.task.prompt}</p><div class="options">${s.task.options.map(o=>`<label class="option"><input type="radio" name="choice" value="${escapeHtml(o)}" ${existing===o?'checked':''} ${done?'disabled':''}><span>${escapeHtml(o)}</span></label>`).join('')}</div><button class="btn burgundy" ${done?'disabled':''} onclick="submitChoice(${s.id})">${done?'Відповідь подано':'Подати відповідь'}</button>${done?'<p class="status ok">Відповідь зафіксовано.</p>':''}</div>`;
return `<div class="task-box"><div class="section-kicker">Завдання команди</div><h3>${s.task.title}</h3><p>${s.task.prompt}</p><div class="field"><textarea id="answerText" ${done?'disabled':''} placeholder="Введіть узгоджену позицію команди...">${escapeHtml(existing)}</textarea></div><button class="btn burgundy" ${done?'disabled':''} onclick="submitText(${s.id})">${done?'Відповідь подано':'Подати відповідь'}</button>${done?'<p class="status ok">Відповідь зафіксовано.</p>':''}</div>`}
window.submitChoice=id=>{const v=document.querySelector('input[name=choice]:checked')?.value;if(!v)return alert('Оберіть варіант');const k=`${state.teamId}-${id}`;state.answers[k]=v;state.submitted[k]=true;save();render()}
window.submitText=id=>{const v=el('answerText').value.trim();if(!v)return alert('Введіть відповідь команди');const k=`${state.teamId}-${id}`;state.answers[k]=v;state.submitted[k]=true;save();render()}
function hero(s){return `<div class="banner"><div class="hero-card"><div class="eyebrow">${escapeHtml(s.kind)} · ${escapeHtml(s.time)}</div><h1>${escapeHtml(s.title)}</h1><p>${escapeHtml(s.intro)}</p><div class="hero-meta"><span class="meta-chip">${escapeHtml(D.caseNo)}</span><span class="meta-chip">Господарська юрисдикція</span><span class="meta-chip">Наскрізна справа</span></div>${s.lecture?`<div class="notice blue"><strong>Міні-лекція:</strong> ${escapeHtml(s.lecture)}</div>`:''}</div><div class="progress-card"><div class="progress-label">Відкрито етапів</div><div class="score">${state.openedStage+1}/${D.stages.length}</div><div class="progress"><div style="width:${progressPct()}%"></div></div><p class="small" style="color:#d9e4eb;margin-top:10px">Команди можуть повертатися до всіх уже відкритих етапів.</p></div></div>`}
function caseSide(s,team){return `<div class="card side-case"><div class="section-kicker">Електронне досьє</div><h3>${escapeHtml(team?.name||'Симуляційна справа')}</h3><div class="case-number">${escapeHtml(D.caseNo)}</div><div class="case-list"><div class="case-item"><span>Сторони</span><b>${escapeHtml(D.parties)}</b></div><div class="case-item"><span>Предмет</span><b>${escapeHtml(D.subject)}</b></div><div class="case-item"><span>Переглядається</span><b>${escapeHtml(s.kind)}: ${escapeHtml(s.title)}</b></div></div></div><div class="card"><div class="section-kicker">Карта ризиків</div><h3 style="margin-bottom:12px">Потенційні види зловживань</h3>${abuseMap(s)}</div>`}
function siteFooter(){return `<footer class="site-footer"><div class="site-footer-inner"><div class="footer-brand"><img src="${NSJU_LOGO}" alt="Емблема Національної школи суддів України"><div><strong>Національна школа суддів України</strong><span>Навчальна інтерактивна симуляція</span></div></div><div class="credit">Розроблено <strong>Оленою Фоновою</strong>, 2026</div></div></footer>`}
function finalScoreboard(){const ranked=D.teams.map(t=>({id:t.id,name:t.name,score:Number(state.scores[t.id]||0)})).sort((a,b)=>b.score-a.score);return `<section class="card final-scoreboard" id="final-scoreboard"><div class="section-kicker">Фінал</div><h2>Підсумковий рахунок команд</h2><p class="muted">Фінальні бали всіх команд після завершення симуляції.</p><div class="final-score-grid">${ranked.map((x,i)=>`<div class="final-score-card"><div class="team-badge">${i+1} місце</div><strong>${escapeHtml(x.name)}</strong><span>${x.score}</span><small>балів</small></div>`).join('')}</div></section>`}
window.toggleFinalScoreboard=()=>{state.finalScoreboardVisible=!state.finalScoreboardVisible;save();render()}
function teamView(){const s=viewed();const team=D.teams.find(t=>t.id===state.teamId);const asym=s.asymmetric?.[state.teamId];return `<div class="shell">${topbar()}<main class="container">${hero(s)}${stageNav()}<div class="layout"><div class="stack"><section class="card"><div class="card-title"><div><div class="section-kicker">Матеріали етапу</div><h2>Документи та процесуальні події</h2></div><span class="meta-chip">${(s.docs||[]).length} матеріалів</span></div><div class="docs">${(s.docs||[]).length?s.docs.map(docCard).join(''):'<div class="notice">На калібрувальному етапі досьє ще не відкривається.</div>'}</div>${asym?`<div class="notice burgundy"><strong>${escapeHtml(asym.title)}</strong><br>${escapeHtml(asym.body)}</div>`:''}</section><section class="card">${taskForm(s)}</section></div><aside class="stack">${caseSide(s,team)}<div class="card"><div class="section-kicker">Результат</div><h3>Бали команди</h3><div class="score" style="color:var(--burgundy)">${state.scores[state.teamId]||0}</div><p class="small muted">Оцінюється аргументація, робота з фактами, розмежування права і зловживання та пропорційність реакції суду.</p></div></aside></div></main>${siteFooter()}</div>`}
function trainerView(){const s=viewed();const total=D.teams.length;const submitted=D.teams.filter(t=>state.submitted[`${t.id}-${s.id}`]).length;const finalBlock=isFinalStage(s)?`<section class="card" style="margin-top:20px"><div class="section-kicker">Завершення симуляції</div><h2>Фінальний рахунок</h2><p class="muted">Після виставлення фінальних балів відкрийте табло для підсумкового показу.</p><button class="btn burgundy" onclick="toggleFinalScoreboard()">${state.finalScoreboardVisible?'Сховати підсумковий рахунок':'Показати підсумковий рахунок'}</button></section>${state.finalScoreboardVisible?finalScoreboard():''}`:'';return `<div class="shell">${topbar()}<main class="container">${hero(s)}${stageNav()}<div class="trainer-grid"><div class="metric"><span class="muted small">Переглядається</span><b>${escapeHtml(s.kind)}</b><span class="small">${escapeHtml(s.title)}</span></div><div class="metric"><span class="muted small">Подали відповідь</span><b>${submitted}/${total}</b><span class="small">команд на цьому етапі</span></div><div class="metric"><span class="muted small">Наступний етап</span><b>${state.openedStage<D.stages.length-1?D.stages[state.openedStage+1].kind:'Фініш'}</b><button class="btn burgundy small-btn" style="margin-top:8px" ${state.openedStage>=D.stages.length-1?'disabled':''} onclick="openNext()">Відкрити</button></div></div><div style="height:20px"></div><div class="layout"><div class="stack"><div class="card"><div class="card-title"><div><div class="section-kicker">Команди</div><h2>Відповіді та оцінювання</h2></div></div>${D.teams.map(t=>{const k=`${t.id}-${s.id}`;const ans=state.answers[k];return `<div class="team-row"><div><span class="team-badge">${t.id}</span><b>${t.name}</b><div class="small muted" style="margin-top:5px">${ans?escapeHtml(ans):'Відповідь ще не подано'}</div></div><div><span class="status ${ans?'ok':'warn'}">${ans?'Подано':'Очікується'}</span></div><div><input id="score-${t.id}" type="number" min="0" max="100" value="${state.scores[t.id]||0}" style="width:95px;padding:9px;border:1px solid var(--line);border-radius:9px"></div><div><button class="btn secondary small-btn" onclick="setScore('${t.id}')">Зберегти</button></div></div>`}).join('')}</div><div class="card"><div class="section-kicker">Матеріали</div><h2 style="margin-bottom:14px">Поточний пакет</h2><div class="docs">${(s.docs||[]).map(docCard).join('')||'<p class="muted">Документів немає.</p>'}</div></div></div><aside class="stack">${caseSide(s,null)}<div class="card"><div class="section-kicker">Керування</div><h3 style="margin-bottom:10px">Демо-режим</h3><button class="btn secondary" onclick="resetDemo()">Скинути локальні дані</button><p class="small muted">У демо дані зберігаються в браузері. Продакшн-версія має використовувати окремий backend.</p></div></aside></div>${finalBlock}</main>${siteFooter()}</div>`}
window.openNext=()=>{if(state.openedStage<D.stages.length-1){state.openedStage++;state.viewedStage=state.openedStage;save();render()}}
window.setScore=id=>{state.scores[id]=Number(el(`score-${id}`).value)||0;save();render()}
window.resetDemo=()=>{if(confirm('Скинути локальні дані гри?')){localStorage.removeItem(key);location.reload()}}
function render(){if(!state.role)return login();el('app').innerHTML=state.role==='trainer'?trainerView():teamView()}
render();
